// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart 
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqrRwJp1o3bfoW-8bJApTGQ7cVkxqwTGU',
    appId: '1:346652509521:web:acb4d449d88410c8683f70',
    messagingSenderId: '346652509521',
    projectId: 'crm-4f33d',
    authDomain: 'crm-4f33d.firebaseapp.com',
    storageBucket: 'crm-4f33d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArdlQ2JNgPDjrVWf14aLqdqthdirhDZps',
    appId: '1:346652509521:android:1f653c9476c0d5b3683f70',
    messagingSenderId: '346652509521',
    projectId: 'crm-4f33d',
    storageBucket: 'crm-4f33d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCDe7Xt3oP47e2G1f2BhrvVlEJan1vXEw',
    appId: '1:346652509521:ios:762cb2605e961f70683f70',
    messagingSenderId: '346652509521',
    projectId: 'crm-4f33d',
    storageBucket: 'crm-4f33d.firebasestorage.app',
    androidClientId:
        '346652509521-dii4hb0vg84sm9h0nd5gqhk59qms5nkf.apps.googleusercontent.com',
    iosClientId:
        '346652509521-abr8spl9h1o46nmou1c8p40b3fjp7k2m.apps.googleusercontent.com',
    iosBundleId: 'com.erpsmart.crm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCDe7Xt3oP47e2G1f2BhrvVlEJan1vXEw',
    appId: '1:346652509521:ios:3187095d82fedd59683f70',
    messagingSenderId: '346652509521',
    projectId: 'crm-4f33d',
    storageBucket: 'crm-4f33d.firebasestorage.app',
    androidClientId:
        '346652509521-dii4hb0vg84sm9h0nd5gqhk59qms5nkf.apps.googleusercontent.com',
    iosClientId:
        '346652509521-b55v86bfjql4qd1500br7nliiisf7k2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.crm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqrRwJp1o3bfoW-8bJApTGQ7cVkxqwTGU',
    appId: '1:346652509521:web:1065aa9e2e44c1dd683f70',
    messagingSenderId: '346652509521',
    projectId: 'crm-4f33d',
    authDomain: 'crm-4f33d.firebaseapp.com',
    storageBucket: 'crm-4f33d.firebasestorage.app',
  );
}
